/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-15 09:18:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.IPostDAO;
import com.service.PostDAO;
import com.bean.Post;
import com.service.CommentDAO;
import com.dao.iCommentDAO;
import java.util.List;
import com.bean.Comment;

public final class post_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dao.IPostDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.service.CommentDAO");
    _jspx_imports_classes.add("com.service.PostDAO");
    _jspx_imports_classes.add("com.bean.Post");
    _jspx_imports_classes.add("com.dao.iCommentDAO");
    _jspx_imports_classes.add("com.bean.Comment");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"author\" content=\"rogepi\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/universal.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/about.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/post.css\" />\r\n");
      out.write("  <script src=\"js/post.js\"></script>\r\n");
      out.write("  <title>CJ FORUM</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"images/rowlet.png\" type=\"image/x-icon\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <h1>CJ FORUM</h1>\r\n");
      out.write("  <p>Everything happens for a reason</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"topnav\">\r\n");
      out.write("  <ul>\r\n");
      out.write("    <li><a href=\"home.jsp\">首页</a></li>\r\n");
      out.write("    <li><a href=\"mine.jsp\">我的</a></li>\r\n");
      out.write("    <li><a href=\"publish.html\">发帖</a></li>\r\n");
      out.write("    <li><a href=\"home_login.jsp\">登录</a></li>\r\n");
      out.write("    <li><a href=\"about.html\">关于</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"card\">\r\n");
      out.write("    ");

      int id = Integer.parseInt(request.getParameter("id"));
      IPostDAO iPostDAO = new PostDAO();
      Post post = new Post();
      post.setId(id);
      Post post1 = null;
      try {
        post1 = iPostDAO.findById(post);
      } catch (Exception e) {
        e.printStackTrace();
      }
      assert post1 != null;
      out.write("\r\n");
      out.write("    <h3>");
      out.print(post1.getTitle());
      out.write("</h3>\r\n");
      out.write("    <div class=\"ifmt\">\r\n");
      out.write("      <div class=\"author\">\r\n");
      out.write("        <p>作者：");
      out.print(post1.getAuthor());
      out.write("</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"type\">\r\n");
      out.write("        <p>类型：");
      out.print(post1.getType());
      out.write("</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"date\">\r\n");
      out.write("        <p>时间：");
      out.print(post1.getDate());
      out.write("</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      ");
      out.print(post1.getContent());
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"card comment\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("      <div class=\"text\">\r\n");
      out.write("        <h3>评论</h3>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"btn\">\r\n");
      out.write("        <button onclick=\"input_show()\">+</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div><br>\r\n");
      out.write("    <div class=\"cinput\" id=\"ci\" style=\"display: none;\">\r\n");
      out.write("      <form action=\"CommentAdd\" method=\"post\">\r\n");
      out.write("        <input type=\"text\" id=\"content\" name=\"content\">\r\n");
      out.write("        <input style=\"display: none\" type=\"text\" id=\"post_id\" name=\"post_id\" value=\"");
      out.print(post1.getId());
      out.write("\">\r\n");
      out.write("        <div class=\"btn\">\r\n");
      out.write("          <button type=\"submit\">评论</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"comments\">\r\n");
      out.write("      ");

        iCommentDAO icommentdao = new CommentDAO();
        List<Comment> comments = null;
        try {
          comments =  icommentdao.findByPostId(post1);
        } catch (Exception e) {
          e.printStackTrace();
        }
        assert comments != null;
        for (Comment comment : comments) {
          
      out.write("\r\n");
      out.write("      <h5>");
      out.print(comment.getAuthor());
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print(comment.getContent());
      out.write("</h5>\r\n");
      out.write("      <br>\r\n");
      out.write("      ");

        }
      
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <h2>Copyright:@Forumsys by rogepi</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
